import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class OrderCreate {
  @ApiProperty()
  order_date: Date;
  @ApiProperty()
  total_amount: string;
  @ApiProperty()
  status: string;
}

export class Order {
  @ApiProperty()
  id: number;
  @ApiProperty()
  order_date: Date;
  @ApiProperty()
  total_amount: string;
  @ApiProperty()
  status: string;
}
